[build]
	command  = "npm run build"
	functions =  "netlify/functions"
	publish = "build"
# for spas
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
[dev]
    command  = "npm run start"
    port = 3000 # Port that the dev server will be listening on
    publish = "build" # Folder with the static content for _redirect file
